### ISSUE TITLE
BCC correctness 예시

### ISSUE THREAD

**Issue by ctaroot** [ldm2468/graph-analysis-tool#31]
Biconnected Components 에 대해서
저번에 알고리즘 정리할 때 썼던 예제를 가지고 돌려보았습니다.

<img width="335" alt="BCC 예시" src="https://user-images.githubusercontent.com/46209460/181021020-992fd408-72e6-482c-b233-ca6b16e29c6a.PNG">

0 1
0 3
1 3
1 4
2 4
2 5
3 4
3 6
3 7
4 5
4 8
5 8

이 예시에서는 articulation point가 2개인데
제가 돌려봤더니 1개로 출력이 됩니다.

한번 확인 부탁드립니다.

**Comment by ldm2468** [comment]
제 컴퓨터에서는 reproduce되지 않습니다.
저는 다음의 결과가 나옵니다.
```
number of articulation points (ARP) = 2
number of biconnected components (BCC) = 4
size of largest biconnected component = 4
maximum number of BCC's connected to a single ARP = 3
```
추가적으로, -f flag로 articulation point 정보를 파일로 출력한 결과는 다음과 같습니다.
```
0 1
1 1
2 1
3 3
4 2
5 1
6 1
7 1
8 1
```
Vertex 3, 4가 articulation point임을 확인할 수 있습니다.

**Comment by ctaroot** [comment]
네 다시 돌려보니까 제대로 돌아가네요
저번에 돌릴때 착오가 있었나봅니다.

감사합니다
