### ISSUE TITLE
eigenCentrality 함수 수행 중 exception 발생

### ISSUE THREAD

**Issue by cakelemon** [ldm2468/graph-analysis-tool#6]
**문제 발생 commit:** 
da5e2f0 - Implement trivial optimization 
(최신 master)

**testcase:** 
(.txt 를 .snap 으로 바꿔야 함)
[wiki-Vote.txt](https://github.com/ldm2468/graph-analysis-tool/files/8596454/wiki-Vote.txt)

**재현 방법:**
```
git checkout da5e2f0
make clean
make all
./main <PATH TO wiki-Vote.snap>
```

**재현 결과:**
```
double free or corruption (!prev)
Aborted
```

**상세**
-Makefile 에서 컴파일 옵션을 -O0 -g 로 바꾸고 VSCode 디버그 모드에서 수행하였다.
![image](https://user-images.githubusercontent.com/22201787/166098519-51c30d4f-7cfd-4777-a582-6d0b2621511e.png)

calcEigenCentrality( ) 함수 수행 후 함수가 종료될 때, 
std::vector<double> mul; 의 소멸자가 불리다가 해당 exception 이 발생.

**참고**
코드를 검토해 보았지만 문제 될 만한 점이 잘 보이지 않아서, 코드의 문제라고 단정할 수는 없었다.
혹시나 빌드 환경 문제, 또는 input data의 문제인지는 아직 면밀히 검토하지는 못한 상태이다.

**Comment by ctaroot** [comment]
75번째 줄에서 vector range를 벗어나는 위치에 접근해서 문제가 생기는 것으로 보입니다.

제 생각으로는 input data의 vertex id가 0부터 n까지가 아닌 임의의 숫자로 되어있어서
vertex id가 n(vertex 개수)보다 커지는 경우가 발생합니다.
ex) wiki-Vote의 vertex 개수는 7115인데 vertex id가 8275인 edge가 있음

**Comment by ldm2468** [comment]
vector를 unordered_map으로 바꿔서 해결했으나, 약간의 성능 저하가 있습니다.
(버그 해결이 오래 걸려서 죄송합니다)
